### ISSUE TITLE
MELPA?

### ISSUE THREAD

**Issue by manuel-uberti** [wandersoncferreira/ivy-clojuredocs#1]
First of all, thanks for taking the time to write an utility such as this.

As per the README, here I am asking the expected question: any chance you can put this on MELPA? :)

**Comment by wandersoncferreira** [comment]
=) glad you enjoy it.

I need some time to write docstrings and improve the readability of the code before applying to MELPA. If you feel that you can help with this approach, it will be nice.

**Comment by wandersoncferreira** [comment]
@manuel-uberti, I submitted a PR at https://github.com/melpa/melpa/pull/6350#issue-304974077

**Comment by manuel-uberti** [comment]
Superb, thank you, I guess we can close this now.
